apiVersion: v1
kind: ServiceAccount
metadata:
  name: orchestrator-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: task-runner-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orchestrator-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orchestrator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: orchestrator-role
subjects:
  - kind: ServiceAccount
    name: orchestrator-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: task-runner-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "get", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: task-runner-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: task-runner-role
subjects:
  - kind: ServiceAccount
    name: task-runner-sa
